name: Manually triggered workflow
on:
  workflow_dispatch:
                   branches: [stage]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Add SSH key
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  mkdir -p /home/runner/.ssh
                  # Replace example.com with the hostname of the machine
                  # you're SSH-ing into
                  ssh-keyscan git.us-5.magento.cloud >> /home/runner/.ssh/known_hosts
                  # DOKKU_SSH_KEY is the name of the repository secret
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
                  chmod 600 /home/runner/.ssh/github_actions
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
                  ssh-add /home/runner/.ssh/github_actions
            - name: Build and deploy
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  ssh -T pbor5wu32tpvs@git.us-5.magento.cloud
