name: Manually triggered workflow
on:
  workflow_dispatch:
jobs:
  deploy-keys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup key      
      uses: ./
      with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}      
      run: |
        ssh -T pbor5wu32tpvs@git.us-5.magento.cloud

