name: Manually triggered workflow
on:
  workflow_dispatch:
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - shell: bash       
      env: 
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "Test"
        mkdir .ssh
        echo "$SSH_KEY" > .ssh/id_rsa
        cat .ssh/id_rsa
